In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("raw_data.csv")

In [3]:
df.shape

(891, 12)

In [4]:
df.duplicated().sum()

np.int64(0)

In [5]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [7]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [8]:
y = df["Embarked"].mode()[0]
df.fillna({"Embarked" : y}, inplace=True)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [9]:
df.shape

(891, 12)

In [10]:
x = df["Age"].mean()
df.fillna({"Age" : x}, inplace=True)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,NaN,Q

In [11]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [12]:
df.drop("Cabin", axis=1, inplace=True)

<p><b>Note : </b> For delete a column - <b>df.drop("col_name", axis = 1)</b></p>

In [13]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [14]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Embarked           str
dtype: object

<p>Fix Data Types</p>

In [15]:
df["Age"] = df["Age"].astype(int)

In [16]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age              int64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Embarked           str
dtype: object

<p>Handle Categorical Data <br>
Convert text → numeric</p>

In [17]:
df["Sex"] = df["Sex"].map({'male' : 0, 'female': 1})
df["Embarked"] = df["Embarked"].map({"S": 0, "C": 1, "Q": 2})

In [18]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",0,22,1,0,A/5 21171,7.2500,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38,1,0,PC 17599,71.2833,1
2,3,1,3,"Heikkinen, Miss. Laina",1,26,0,0,STON/O2. 3101282,7.9250,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35,1,0,113803,53.1000,0
4,5,0,3,"Allen, Mr. William Henry",0,35,0,0,373450,8.0500,0

<p>Drop Irrelevant Columns. These don’t help much in analysis</p>

In [19]:
df.drop(["PassengerId", "Name", "Ticket"], axis=1, inplace=True)

In [20]:
df.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'Embarked'],
      dtype='str')

In [21]:
df.shape

(891, 8)

In [22]:
df.duplicated().sum()

np.int64(117)

In [23]:
df[df.duplicated()]

     Survived  Pclass  Sex  Age  SibSp  Parch     Fare  Embarked
47          1       3    1   29      0      0   7.7500         2
76          0       3    0   29      0      0   7.8958         0
77          0       3    0   29      0      0   8.0500         0
87          0       3    0   29      0      0   8.0500         0
90          0       3    0   29      0      0   8.0500         0
..        ...     ...  ...  ...    ...    ...      ...       ...
870         0       3    0   26      0      0   7.8958         0
877         0       3    0   19      0      0   7.8958         0
878         0       3    0   29      0      0   7.8958         0
884         0       3    0   25      0      0   7.0500         0
886         0       2    0   27      0      0  13.0000         0

[117 rows x 8 columns]

In [24]:
df.drop_duplicates(inplace=True)

In [25]:
df.describe()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
count,774.000000,774.000000,774.000000,774.000000,774.000000,774.000000,774.000000,774.000000
mean,0.413437,2.241602,0.375969,29.693798,0.529716,0.421189,35.031045,0.347545
std,0.492768,0.855558,0.484685,13.770548,0.990783,0.840973,52.415006,0.611987
min,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,1.000000,0.000000,21.000000,0.000000,0.000000,8.050000,0.000000
50%,0.000000,3.000000,0.000000,29.000000,0.000000,0.000000,16.100000,0.000000
75%,1.000000,3.000000,1.000000,36.000000,1.000000,1.000000,34.375000,1.000000
max,1.000000,3.000000,1.000000,80.000000,8.000000,6.000000,512.329200,2.000000

<p>Last Checking</p>

In [26]:
df.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [27]:
df.info()

<class 'pandas.DataFrame'>
Index: 774 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  774 non-null    int64
 1   Pclass    774 non-null    int64
 2   Sex       774 non-null    int64
 3   Age       774 non-null    int64
 4   SibSp     774 non-null    int64
 5   Parch     774 non-null    int64
 6   Fare      774 non-null    float64
 7   Embarked  774 non-null    int64
dtypes: float64(1), int64(7)
memory usage: 54.4 KB

In [28]:
df.to_csv("clean_data.csv", index=False)

In [29]:
df.shape

(774, 8)

<p>Filtering Example - </p>

In [34]:
df.loc[200:210, ['Sex', 'Survived']]

     Sex  Survived
200    0         0
202    0         0
203    0         0
204    0         1
205    1         0
206    0         0
207    0         1
208    1         1
209    0         1
210    0         0

In [30]:
df.groupby('Sex').sum()

     Survived  Pclass    Age  SibSp  Parch        Fare  Embarked
Sex
0         105    1119  14826    220    129  13618.8662       146
1         215     616   8157    190    197  13495.1627       123

In [33]:
df.groupby("Sex")['Sex'].count()

Sex
0    483
1    291
Name: Sex, dtype: int64

<p>Here , df.groupby("Sex") : Splits the dataset into groups based on unique values in the "Sex" column. Then ["Sex"] : From each group, we are selecting the "Sex" column again.</p>